//
//  TrackingEvent.swift
//  KyberNetwork
//
//  Created by Tung Nguyen on 21/07/2022.
//

import Foundation

enum TrackingEvent: String {
  case scanOpen = "scan_open"
  case scanText = "scan_text"
  case screenImportWallet = "screen_import_wallet"
  case iwJSONSuccess = "iw_json_success"
  case iwPKSuccess = "iw_pk_success"
  case iwSeedSuccess = "iw_seed_success"
  case iwJSONFail = "iw_json_fail"
  case iwPKFail = "iw_pk_fail"
  case iwSeedFail = "iw_seed_fail"
  case openEarnSwapView = "krystal_open_earn_swap_view"
  case transferCancel = "transfer_cancel"
  case openApp = "krystal_open_app_event"
  case introCreateWallet = "intro_create_wallet"
  case introImportWallet = "intro_import_wallet"
  case cwSuccess = "cw_success"
  case cwTryAgain = "cw_try_again"
  case cwBackupAgain = "cw_backup_again"
  case cwSkipConfirm = "cw_skip_confirm"
  case cwConfirm = "cw_confirm"
  case marketOpenDetail = "market_open_detail"
  case dappShowAllHistory = "dapp_show_all_history"
  case dappBack = "dapp_back"
  case dappForward = "dapp_forward"
  case dappRefresh = "dapp_refresh"
  case dappShare = "dapp_share"
  case dappCopy = "dapp_copy"
  case dappFavorite = "dapp_favorite"
  case dappSwitchChain = "dapp_switch_chain"
  case dappSwitchWallet = "dapp_switch_wallet"
  case dappDeleteAllHistory = "dapp_delete_all_history"
  case dappDeleteHistory = "dapp_delete_history"
  case swapSpeedup = "swap_speedup"
  case earnSpeedup = "earn_speedup"
  case transferSpeedup = "transfer_speedup"
  case transferClickMultipleTransfer = "transfer_click_multiple_transfer"
  case multisendBarcodeScan = "multiple_transfer_barcode_scan"
  case multisendContactBook = "multiple_transfer_contact_book"
  case multisendRemoveReceiver = "multiple_transfer_remove_receiver"
  case multisendAddReceiver = "multiple_transfer_add_receiver"
  case multisendApprove = "multiple_transfer_approve"
  case multisendConfirm = "multiple_transfer_confirm"
  case swapCancel = "swap_cancel"
  case swapSubmit = "swap_submit"
  case manageTokenSelectAll = "manage_token_select_all"
  case manageTokenDeselectAll = "manage_token_deselect_all"
  case earnSubmit = "earn_submit"
  case introSwipeOnboard = "intro_swipe_onboard"
  case openEarnView = "krystal_open_earn_view"
  case manageTokenSearch = "manage_token_search"
  case tokenChangeDisable = "token_change_disable"
  case tokenDelete = "token_delete"
  case tokenEdit = "token_edit"
  case marketSortName = "market_sort_name"
  case marketSort24h = "market_sort_24h"
  case marketSortVol = "market_sort_vol"
  case marketSortPrice = "market_sort_price"
  case marketSortCap = "market_sort_cap"
  case marketSwitch24h = "market_switch_24h"
  case marketSwitchCap = "market_switch_cap"
  case openSwapView = "krystal_open_swap_view"
  case transferSubmit = "transfer_submit"
  case openSendView = "krystal_open_send_view"
  case earnCancel = "earn_cancel"
  case exploreMultisend = "explore_multiple_transfer"
  case promotionClaim = "promotion_claim"
}
