//
//  AdvanceSearchTokenProtocols.swift
//  KyberNetwork
//
//  Created Com1 on 13/06/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol AdvanceSearchTokenWireframeProtocol: class {
  func openChartTokenView(token: Token, currencyMode: CurrencyMode)
}
//MARK: Presenter -
protocol AdvanceSearchTokenPresenterProtocol: class {
  var recommendTags: [String] { get }
  var dataSource: [OverviewMainCellViewModel] { get }
  var searchText: String { get set }
  func reloadAllData()
  func openChartToken(token: Token)
  func saveNewSearchTag(_ tag: String)
  func getRecentSearchTag() -> [String]
}

//MARK: Interactor -
protocol AdvanceSearchTokenInteractorProtocol: class {

  var presenter: AdvanceSearchTokenPresenterProtocol?  { get set }
}

//MARK: View -
protocol AdvanceSearchTokenViewProtocol: class {

  var presenter: AdvanceSearchTokenPresenterProtocol!  { get set }
}
