//
//  AdvanceSearchTokenRouter.swift
//  KyberNetwork
//
//  Created Com1 on 13/06/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AdvanceSearchTokenRouter: AdvanceSearchTokenWireframeProtocol {
    
  weak var viewController: UIViewController?
    
  static func createModule(currencyMode: CurrencyMode) -> UIViewController {
    // Change to get view from storyboard if not using progammatic UI
    let view = OverviewSearchTokenViewController()
    let interactor = AdvanceSearchTokenInteractor()
    let router = AdvanceSearchTokenRouter()
    let presenter = AdvanceSearchTokenPresenter(interface: view, interactor: interactor, router: router)
    presenter.currencyMode = currencyMode
    view.presenter = presenter
    interactor.presenter = presenter
    router.viewController = view
    return view
  }
  
  func openChartTokenView(token: Token, currencyMode: CurrencyMode) {
    let viewModel = ChartViewModel(token: token, currencyMode: currencyMode)
    let controller = ChartViewController(viewModel: viewModel)
    viewController?.navigationController?.pushViewController(controller, animated: true)
  }
}
