//
//  AdvanceSearchTokenPresenter.swift
//  KyberNetwork
//
//  Created Com1 on 13/06/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AdvanceSearchTokenPresenter: AdvanceSearchTokenPresenterProtocol {
  weak private var view: AdvanceSearchTokenViewProtocol?
  var interactor: AdvanceSearchTokenInteractorProtocol?
  private let router: AdvanceSearchTokenWireframeProtocol

  var dataSource: SearchResult?
  var currencyMode: CurrencyMode = .usd
  var recommendTags: [String] {
    return KNGeneralProvider.shared.currentChain.recommendTags()
  }

  func doSearch(keyword: String) {
    view?.showLoading()
    interactor?.getSearchData(keyword: keyword)
  }

  func reloadAllData(result: SearchResult?) {
    view?.hideLoading()
    guard let result = result else {
      dataSource = nil
      view?.reloadData()
      return
    }

    
    if result.tokens.isNotEmpty || result.portfolios.isNotEmpty {
      dataSource = result
    }
    view?.reloadData()
  }
  
  func getRecentSearchTag() -> [String] {
    if let tags = UserDefaults.standard.object(forKey: KNEnvironment.default.envPrefix + "Recent-search") as? [String] {
      return tags
    } else {
      return []
    }
  }
  
  func saveNewSearchTag(_ tag: String) {
    if var tags = UserDefaults.standard.object(forKey: KNEnvironment.default.envPrefix + "Recent-search") as? [String] {
      if !tags.contains(tag) {
        tags.append(tag)
        if tags.count > 8 {
          tags.remove(at: 0)
        }
        UserDefaults.standard.setValue(tags, forKey: KNEnvironment.default.envPrefix + "Recent-search")
      }
    } else {
      UserDefaults.standard.setValue([tag], forKey: KNEnvironment.default.envPrefix + "Recent-search")
    }
  }
  
  func openChartToken(token: Token) {
    KNCrashlyticsUtil.logCustomEvent(withName: "market_open_detail", customAttributes: nil)
    router.openChartTokenView(token: token, currencyMode: self.currencyMode)
  }

  init(interface: AdvanceSearchTokenViewProtocol, interactor: AdvanceSearchTokenInteractorProtocol?, router: AdvanceSearchTokenWireframeProtocol) {
      self.view = interface
      self.interactor = interactor
      self.router = router
  }

}
