//
//  AdvanceSearchTokenInteractor.swift
//  KyberNetwork
//
//  Created Com1 on 13/06/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AdvanceSearchTokenInteractor: AdvanceSearchTokenInteractorProtocol {

    weak var presenter: AdvanceSearchTokenPresenterProtocol?
}
