//
//  AdvanceSearchTokenProtocols.swift
//  KyberNetwork
//
//  Created Com1 on 13/06/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//
import UIKit
import Foundation

//MARK: Wireframe -
protocol AdvanceSearchTokenWireframeProtocol: class {
  var coordinator: OverviewCoordinator? { get set }
  func createModule(currencyMode: CurrencyMode, coordinator: OverviewCoordinator) -> UIViewController
  func openChartTokenView(token: ResultToken, currencyMode: CurrencyMode)
}
//MARK: Presenter -
protocol AdvanceSearchTokenPresenterProtocol: class {
  var recommendTags: [String] { get }
  var searchResults: SearchResult? { get set }
  var isShowAll: Bool { get set }
  func didGetSearchResult(result: SearchResult?, error: Error?)
  func doSearch(keyword: String)
  func openChartToken(token: ResultToken)
  func saveNewSearchTag(_ tag: String)
  func getRecentSearchTag() -> [String]
  func numberOfRows(section: Int) -> Int
  func shouldShowEmpty() -> Bool
}

//MARK: Interactor -
protocol AdvanceSearchTokenInteractorProtocol: class {
  var presenter: AdvanceSearchTokenPresenterProtocol?  { get set }
  func getSearchData(keyword: String)
}

//MARK: View -
protocol AdvanceSearchTokenViewProtocol: class {
  var presenter: AdvanceSearchTokenPresenterProtocol!  { get set }
  func reloadData()
  func showLoading()
  func hideLoading()
  func showError(msg: String)
}
