//
//  AdvanceSearchTokenPresenter.swift
//  KyberNetwork
//
//  Created Com1 on 13/06/2022.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AdvanceSearchTokenPresenter: AdvanceSearchTokenPresenterProtocol {
  weak private var view: AdvanceSearchTokenViewProtocol?
  var interactor: AdvanceSearchTokenInteractorProtocol?
  private let router: AdvanceSearchTokenWireframeProtocol
  
  
  var searchText = ""
  var dataSource: [OverviewMainCellViewModel] = []
  var currencyMode: CurrencyMode = .usd
  var recommendTags: [String] {
    return KNGeneralProvider.shared.currentChain.recommendTags()
  }
  
  func reloadAllData() {
    guard !self.searchText.isEmpty else {
      self.dataSource.removeAll()
      return
    }
    
    var tokens = KNSupportedTokenStorage.shared.allActiveTokens
    tokens = tokens.filter({ (item) -> Bool in
      return item.symbol.lowercased().contains(self.searchText.lowercased())
    })
    tokens.sort { (left, right) -> Bool in
      return left.symbol < right.symbol
    }
    let viewModels = tokens.map { (token) -> OverviewMainCellViewModel in
      return OverviewMainCellViewModel(mode: .search(token: token), currency: self.currencyMode)
    }
    self.dataSource = viewModels
  }
  
  func getRecentSearchTag() -> [String] {
    if let tags = UserDefaults.standard.object(forKey: KNEnvironment.default.envPrefix + "Recent-search") as? [String] {
      return tags
    } else {
      return []
    }
  }
  
  func saveNewSearchTag(_ tag: String) {
    if var tags = UserDefaults.standard.object(forKey: KNEnvironment.default.envPrefix + "Recent-search") as? [String] {
      if !tags.contains(tag) {
        tags.append(tag)
        if tags.count > 8 {
          tags.remove(at: 0)
        }
        UserDefaults.standard.setValue(tags, forKey: KNEnvironment.default.envPrefix + "Recent-search")
      }
    } else {
      UserDefaults.standard.setValue([tag], forKey: KNEnvironment.default.envPrefix + "Recent-search")
    }
  }
  
  func openChartToken(token: Token) {
    KNCrashlyticsUtil.logCustomEvent(withName: "market_open_detail", customAttributes: nil)
    router.openChartTokenView(token: token, currencyMode: self.currencyMode)
  }

  init(interface: AdvanceSearchTokenViewProtocol, interactor: AdvanceSearchTokenInteractorProtocol?, router: AdvanceSearchTokenWireframeProtocol) {
      self.view = interface
      self.interactor = interactor
      self.router = router
  }

}
