name: Get macOS runner info

on:
  workflow_dispatch:
  push:
    branches:
      - get-runner-info

concurrency: 
  group: manual-debug-fda-dev-${{ github.ref }}
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  
jobs:

  build-ios:
    runs-on: macos-12
    steps:
      - name: Get configuration items
        run: |
          system_profiler
