name: Testflight

on:
  push:
    branches:
      - 'release-*'
      - feat/tf-workflow-1

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  # # base64 service account credentials
  # GCS_SA_CREDENTIAL: ${{ secrets.GCS_SA_CREDENTIAL }}
  # GCS_PROJECT_ID: ${{ secrets.GCS_PROJECT_ID }}
  # GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  build-ios-and-upload-testflight:
    runs-on: macos-12
    env:
      TMP_KEYCHAIN_NAME: "fastlane_tmp_keychain"
      # cetificate environment
      DISTRIBUTE_CERT_PATH: /Users/runner/privates/certificates/devops_testflight.p12
      DISTRIBUTE_CERT_PASSWORD: ${{ secrets.DISTRIBUTE_CERT_PASSWORD }}
      DEVELOPMENT_CERT_PATH: /Users/runner/privates/certificates/devops_development.p12
      DEVELOPMENT_CERT_PASSWORD: ${{ secrets.DEVELOPMENT_CERT_PASSWORD }}
      # xcode project environment
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}     # G9CRYMTLBL
      APPLE_BUNDLE_ID: ${{ secrets.APPLE_BUNDLE_ID }}
      APPLE_CODE_SIGNING_ID: ${{ secrets.APPLE_TESTFIGHT_SIGNING_ID }}
      # profiles
      DEV_PROFILE: ${{ secrets.DEV_PROFILE }}                   # dev_profile
      KRYSTAL_DEV_PROFILE: ${{ secrets.KRYSTAL_DEV_PROFILE }}   # Krytal Dev
      AD_HOC_PROFILE: ${{ secrets.AD_HOC_PROFILE }}             # Krystal_ci_cd_adhoc
      EXT_AD_HOC_PROFILE: ${{ secrets.EXT_AD_HOC_PROFILE }}     # Krystal_extension_ci_cd_adhoc
      KRYSTAL_PROD_PROFILE: ${{ secrets.KRYSTAL_PROD_PROFILE }} 
      KRYSTAL_PROD_EXT_PROFILE: ${{ secrets.KRYSTAL_PROD_EXT_PROFILE }}
      # profile paths
      DEV_PROFILE_PATH: "/Users/runner/privates/profiles/${{ secrets.DEV_PROFILE }}.mobileprovision"
      KRYSTAL_DEV_PROFILE_PATH: "/Users/runner/privates/profiles/${{ secrets.KRYSTAL_DEV_PROFILE }}.mobileprovision"
      AD_HOC_PROFILE_PATH: "/Users/runner/privates/profiles/${{ secrets.AD_HOC_PROFILE }}.mobileprovision"
      EXT_AD_HOC_PROFILE_PATH: "/Users/runner/privates/profiles/${{ secrets.EXT_AD_HOC_PROFILE }}.mobileprovision"
      KRYSTAL_PROD_PROFILE_PATH: "/Users/runner/privates/profiles/${{ secrets.KRYSTAL_PROD_PROFILE }}.mobileprovision"
      KRYSTAL_PROD_EXT_PROFILE_PATH: "/Users/runner/privates/profiles/${{ secrets.KRYSTAL_PROD_EXT_PROFILE }}.mobileprovision"
      # sentry environments
      SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
      ORG_SLUG: ${{ secrets.ORG_SLUG }}
      PROJECT_SLUG: ${{ secrets.PROJECT_SLUG }}
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      # default actor
      GH_ACTOR: Krystal-CICD
      # testflight
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
      APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
      # GCP 
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      IOS_PASSPHRASE: ${{ secrets.IOS_PASSPHRASE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: '${{ secrets.KRYSTAL_BOT_GH_PAT }}'

      - name: Get configuration items
        run: |
          echo $SSH_PRIVATE_KEY | base64 --decode > private.key

          chmod 600 private.key
                    
          rm -rf $HOME/krystal-mobile-enviroment

          GIT_SSH_COMMAND='ssh -i private.key -o IdentitiesOnly=yes -o StrictHostKeyChecking=no' git clone git@github.com:KYRDTeam/krystal-mobile-enviroment.git $HOME/krystal-mobile-enviroment
          
          ls -al $HOME/krystal-mobile-enviroment/
          
          
          CONFIG_PATH=$HOME/krystal-mobile-enviroment/ios/
          ls -al $CONFIG_PATH
          
          echo "Using gpg to decrypt the sensitive files now"

          gpg --quiet --batch --yes --decrypt --passphrase=$IOS_PASSPHRASE $CONFIG_PATH/certificates/devops_development.p12.gpg > $CONFIG_PATH/certificates/devops_development.p12
          gpg --quiet --batch --yes --decrypt --passphrase=$IOS_PASSPHRASE $CONFIG_PATH/certificates/devops_testflight.p12.gpg > $CONFIG_PATH/certificates/devops_testflight.p12
          gpg --quiet --batch --yes --decrypt --passphrase=$IOS_PASSPHRASE $CONFIG_PATH/certificates/distribution.p12.gpg > $CONFIG_PATH/certificates/distribution.p12
          gpg --quiet --batch --yes --decrypt --passphrase=$IOS_PASSPHRASE $CONFIG_PATH/profiles/devops_ios_distribution.mobileprovision.gpg > $CONFIG_PATH/profiles/devops_ios_distribution.mobileprovision
          gpg --quiet --batch --yes --decrypt --passphrase=$IOS_PASSPHRASE $CONFIG_PATH/profiles/devops_ios_ext_distribution.mobileprovision.gpg > $CONFIG_PATH/profiles/devops_ios_ext_distribution.mobileprovision

          ls -al $CONFIG_PATH

          mkdir -p /Users/runner/privates        
          cp -va $CONFIG_PATH/* /Users/runner/privates

          brew install coreutils
          md5sum $DEV_PROFILE_PATH
          # md5sum $KRYSTAL_DEV_PROFILE_PATH
          md5sum $AD_HOC_PROFILE_PATH
          md5sum $EXT_AD_HOC_PROFILE_PATH
          md5sum $KRYSTAL_PROD_PROFILE_PATH
          md5sum $KRYSTAL_PROD_EXT_PROFILE_PATH
      
          

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
          
      - name: Install Pod check
        run: gem install cocoapods-check

      - name: Setup Sentry CLI
        shell: bash
        run: curl -sL https://sentry.io/get-cli/ | bash

      # - name: Setup Auth
      #   uses: 'google-github-actions/auth@v0'
      #   with:
      #     credentials_json: '${{ secrets.GCS_SA_CREDENTIAL }}'

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v0

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Setup environments
        shell: bash
        env:
          ENV: prod
        run: |
          cp /Users/runner/privates/environments/KNSecret.swift ./KyberNetwork/KyberNetwork/Configurations/Environments
          cp /Users/runner/privates/environments/$ENV/KNEnvironment.swift ./KyberNetwork/KyberNetwork/Configurations/Environments/Sources

      - name: Pods install
        run: pod check || pod install

      - name: Build and Upload to Testflight
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: pre_release
          bundle-install-path: "vendor/bundle"

      - name: Prepare bump build number
        run: |
          git config user.name "$GH_ACTOR"
          git config user.email "$GH_ACTOR@users.noreply.github.com"

      - name: Bump Build number
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: ci_bump_build_number
          bundle-install-path: "vendor/bundle"

      - name: Push commit 
        shell: bash
        run: | 
          git push --repo="https://$GH_ACTOR:$KRYSTAL_BOT_GH_PAT@github.com/${GITHUB_REPOSITORY}.git"

      # This step will automatically run if any of the previous steps fail.
      # DO NOT CHANGE IT
      - name: Send notifications to a specify Telegram group
        if: failure()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
          RUN_ID: ${{ github.run_id }}
        shell: bash
        run: .github/failure

  notify-testflight:
    needs:
      - build-ios-and-upload-testflight
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification on Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: release-krystal-ios-testflight
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ':rocket: Krystal-iOS | A new release has been built on TestFlight'
          SLACK_TITLE: ':rocket: Krystal-iOS | A new release has been built on TestFlight'
          SLACK_USERNAME: deployment-notifier
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TF_IOS }}
  
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_CHANNEL: release-krystal-ios-testflight
          SLACK_COLOR: 'fc5a03'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ':rocket: Krystal-iOS | A new release failed to build on TestFlight'
          SLACK_TITLE: ':rocket: Krystal-iOS | A new release failed to build on TestFlight'
          SLACK_USERNAME: deployment-notifier
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TF_IOS }}


### iOS
# Testflight
# devops_distribution
